blog/urls.py
from django.urls import path
from . import views
from .api import viewsets as api_viewsets

app_name = "blog"

blog_list = api_viewsets.BlogAPI.as_view({"get": "list"})
blog_detail = api_viewsets.BlogAPI.as_view({"get": "retrieve", "post": "create"})

urlpatterns = [
    path("blogs", views.BlogList.as_view(), name="Blogs-List"),
    path("blogs/<int:pk>", views.BlogDetail.as_view(), name="Blog-Detail"),
    path("blogs/search", views.BlogSearch.as_view(), name="Blog-Search"),
    path(
        "blogs/categories/<slug:category>/",
        views.CategoryView.as_view(),
        name="Blog-Category",
    ),
    path("blogs/tags/<slug:tag>/", views.TagView.as_view(), name="Blog-Tag"),
    ######## API ########
    path("api/blogs/", blog_list, name="api_blog_list"),
    path("api/blogs/<int:pk>/", blog_detail, name="api_blog_detail"),
    path("api/blogs/search/", api_viewsets.BlogSearchAPI.as_view(), name="api_blog_search"),
    path("api/blogs/categories/", api_viewsets.CategoryAPI.as_view(), name="api_categories"),
    path("api/blogs/categories/<slug:category>/", api_viewsets.BlogsByCategoryAPI.as_view(), name="api_blog_category"),
    path("api/blogs/tags/", api_viewsets.TagAPI.as_view(), name="api_tags"),
    path("api/blogs/tags/<slug:tag>/", api_viewsets.BlogsByTagAPI.as_view(), name="api_blog_tag"),
]

home_property_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from contact.views import ContactView
from contact.api.viewsets import ContactAPI

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("property.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("users.api.urls", namespace="users_api")),
    path("", include("property.api.urls", namespace="property_api")),
    path("contact/", ContactView, name="contact"),
    path("api/contact/", ContactAPI.as_view(), name="api_contact"),
    path("accounts/", include("users.urls", namespace="users")),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "home_property_project.views.page_not_found_view"

property/api/urls.py
from django.urls import path
from . import viewsets as api_viewsets

app_name = "api_property"

property_list = api_viewsets.PropertyAPI.as_view({"get": "list"})
property_detail = api_viewsets.PropertyAPI.as_view({"get": "retrieve", "put": "update", "delete": "destroy"})

urlpatterns = [
    path("api/properties/", property_list, name="api_property_list"),
    path("api/properties/<int:pk>/", property_detail, name="api_property_detail"),
    path("api/search/", api_viewsets.SearchAPI.as_view(), name="api_search_property"),
    path("api/search-form-data/", api_viewsets.SearchFormDataAPI.as_view(), name="api_search_form_data"),
    path("api/user-properties/<str:username>/", api_viewsets.UserPropertyListAPI.as_view(), name="api_user_property"),
    path("api/properties/create/", api_viewsets.CreatePropertyAPI.as_view(), name="api_create_property"),
    
]

property/urls.py
from django.urls import path
from . import views

app_name = "property"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="Home-Page"),
    path("properties/", views.PropertiesList.as_view(), name="Properties-List"),
    path("properties/<int:pk>/", views.PropertyDetailView.as_view(), name="Properties-Detail"),
    path("properties/users/<str:username>/", views.UserPropertiesListView.as_view(), name="user-properties"),
    path("properties/search/", views.SearchView.as_view(), name="Search"),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import PasswordResetForm


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path("login/", views.LoginView.as_view(), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<str:username>', views.profile, name='profile'),
    path("property/new/", views.PropertyCreateView.as_view(), name = "create-property"),
    path("change-password/", views.ChangePasswordView.as_view(), name = "change-password"),
    path('post/<int:pk>/update/', views.PropertyUpdateView.as_view(), name='property-update'),
    path("property/<int:pk>/update/", views.PropertyUpdateView.as_view(), name = "update-property"),
    path("property/<int:pk>/delete/", views.PropertyDeleteView.as_view(), name = "delete-property"),
    # password reset
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        form_class=PasswordResetForm,
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy("users:password_reset_complete")),
        name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

property/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class Property(models.Model):
    property_choices = [
        ('FS', 'For Sale'),
        ('FR', 'For Rent'),
        ('SL', 'Sold Out')
    ]
    STATUS = [
        ('Nor', 'Normal'),
        ('Exc', 'Exclusive')
    ]
    status = models.CharField(max_length=3, choices=STATUS, default='Nor')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    title = models.CharField(max_length=255, verbose_name = "Title")
    property_status = models.CharField(max_length = 2, choices = property_choices, verbose_name = "Property status")
    address = models.CharField(max_length=255, verbose_name = "Address")
    state = models.CharField(max_length=255, verbose_name = "State")
    city = models.CharField(max_length=255, verbose_name = "City")
    description = models.TextField(blank = True, verbose_name = 'Description')
    category = models.ForeignKey("Category", related_name = "property", verbose_name = "Category", on_delete = models.CASCADE, blank = True, null=True)
    price = models.PositiveIntegerField(verbose_name = 'Price')
    bedrooms = models.PositiveIntegerField(verbose_name = 'Bedrooms', default = 0)
    bathrooms = models.PositiveIntegerField(verbose_name = 'Bathrooms', default = 0)
    garage = models.PositiveIntegerField(default = 0, verbose_name = 'Garage')
    sqft = models.PositiveIntegerField(verbose_name = "Area", help_text = 'in SQFT')
    MainPhoto = models.ImageField(upload_to = "Properties/")
    photo_1 = models.ImageField(upload_to = "Properties/", blank = True, null = True)
    photo_2 = models.ImageField(upload_to = "Properties/", blank = True, null = True)
    photo_3 = models.ImageField(upload_to = "Properties/", blank = True, null = True)
    photo_4 = models.ImageField(upload_to = "Properties/", blank = True, null = True)
    photo_5 = models.ImageField(upload_to = "Properties/", blank = True, null = True)
    photo_6 = models.ImageField(upload_to = "Properties/", blank = True, null = True)
    views = models.IntegerField(default = 0)
    pub_date = models.DateTimeField(auto_now_add = True)
    update_date = models.DateTimeField(auto_now = True, auto_now_add = False)
    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Property'
        verbose_name_plural = 'Properties'
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('property:Properties-Detail', kwargs={'pk': self.pk})
    
class Category(models.Model):
    title = models.CharField(verbose_name = "Title", max_length = 50)
    slug = models.SlugField(verbose_name = "Slug")
    
    class Meta:
        verbose_name_plural = "Categories"
        
    def __str__(self):
        return self.title
    
    @classmethod
    def get_categories(cls):
        """Returns all categories titles for field choices used in serializers"""
        return [(category.id, category.title) for category in cls.objects.all()]
    

property/forms.py
from django import forms
from .models import Category


class SearchForm(forms.Form):
    location = forms.CharField(
        max_length=20,
        min_length=3,
        required=False,
        label="Location",
        widget=forms.TextInput(attrs={"placeholder": "Type your location", "type": "text"}),
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(),
        required=False,
        empty_label="Category",
    )
    look_for = forms.ChoiceField(
        choices=[
            (None, "Look for"),
            ("FS", "For Sale"),
            ("FR", "For Rent"),
            ("SL", "Sold Out"),
        ],
        required=False,
    )
    # sqft slider
    min_sqft = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={"type": "hidden", "id": "min_sqft"}))
    max_sqft = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={"type": "hidden", "id": "max_sqft"}))
    # price slider
    min_price = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={"type": "hidden", "id": "min_price"}))
    max_price = forms.IntegerField(required=False, widget=forms.HiddenInput(attrs={"type": "hidden", "id": "max_price"}))

    sort_by = forms.ChoiceField(
        choices=[("pub_date", "Date"), ("title", "Name"), ("price", "Price")],
        required=False,
        widget=forms.Select(),
    )
    paginate_by = forms.ChoiceField(
        choices=[("6", "6"), ("12", "12"), ("18", "18"), ("24", "24")],
        required=False,
        widget=forms.Select(),
    )

property/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from .models import Property
from blog.models import Blog
from django.db.models import Q, F
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormMixin
from .forms import SearchForm
from django.core.paginator import Paginator, EmptyPage


class MyPaginator(Paginator):
    def validate_number(self, number):
        try:
            return super().validate_number(number)
        except EmptyPage:
            if int(number) > 1:
                # return the last page
                return self.num_pages
            elif int(number) < 1:
                # return the first page
                return 1
            else:
                raise


class HomePageView(TemplateView, FormMixin):
    template_name = "property/index.html"
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context["properties"] = Property.objects.all().order_by("-pub_date")[:6]
        context["exclusive_properties"] = Property.objects.filter(status="Exc")
        context["blogs"] = Blog.objects.all().select_related("author").prefetch_related("comments").order_by("-pub_date")[:3]
        return context


class PropertiesList(ListView, FormMixin):
    model = Property
    template_name = "property/properties-list.html"
    context_object_name = "properties"
    paginate_by = 6
    paginator_class = MyPaginator
    form_class = SearchForm

    def get_context_data(self, *args, **kwargs):
        context = super(PropertiesList, self).get_context_data(*args, **kwargs)
        context["popular_properties"] = Property.objects.order_by("-views")[:3]
        return context

    def get_paginate_by(self, queryset):
        if self.request.GET.get("paginate_by") == "":
            return self.paginate_by
        return self.request.GET.get("paginate_by", self.paginate_by)

    def get_ordering(self):
        return f"-{self.request.GET.get('sort_by', 'pub_date')}"

    def get_initial(self):
        return {"sort_by": self.request.GET.get("sort_by", "Date"), "paginate_by": self.request.GET.get("paginate_by", "6")}
    
        
class PropertyDetailView(DetailView, FormMixin):
    model = Property
    template_name = "property/properties-detail.html"
    context_object_name = "property"
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["nearby_properties"] = Property.objects.filter(city=self.object.city).exclude(id=self.object.pk).order_by("?")[:2]
        context["popular_properties"] = Property.objects.exclude(id=self.object.pk).order_by("-views")[:3]
        return context

    def get_object(self):
        obj = super().get_object()
        obj.views = F("views") + 1
        obj.save()
        obj.refresh_from_db()
        return obj
    

class UserPropertiesListView(ListView, FormMixin):
    template_name = "property/properties-list.html"
    context_object_name = "properties"
    paginate_by = 6
    paginator_class = MyPaginator
    form_class = SearchForm

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get("username"))
        return Property.objects.filter(author=user).order_by(f"-{self.request.GET.get('sort_by', 'pub_date')}")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_properties"] = Property.objects.order_by("-views")[:3]
        return context
    
    def get_paginate_by(self, queryset):
        if self.request.GET.get("paginate_by") == "":
            return self.paginate_by
        return self.request.GET.get("paginate_by", self.paginate_by)
    
    def get_ordering(self):
        return f"-{self.request.GET.get('sort_by', 'pub_date')}"
    
    def get_initial(self):
        return {"sort_by": self.request.GET.get("sort_by", "Date"), "paginate_by": self.request.GET.get("paginate_by", "6")}


class SearchView(ListView, FormMixin):
    template_name = "property/properties-list.html"
    context_object_name = "properties"
    paginate_by = 6
    paginator_class = MyPaginator    
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_properties"] = Property.objects.order_by("-views")[:3]
        return context

    def get_paginate_by(self, queryset):
        if self.request.GET.get("paginate_by") == "":
            return self.paginate_by
        return self.request.GET.get("paginate_by", self.paginate_by)

    def get_ordering(self):
        return f"-{self.request.GET.get('sort_by', 'pub_date')}"

    def get_queryset(self):
        request = self.request.GET
        queryset = Property.objects.all()
        if request.get("location"):
            queryset = queryset.filter(Q(city__icontains=request.get("location")))
        if request.get("category"):
            queryset = queryset.filter(Q(category=request.get("category")))
        if request.get("look_for"):
            queryset = queryset.filter(Q(property_status=request.get("look_for")))
        if request.get("min_sqft") or request.get("max_sqft"):
            queryset = queryset.filter(Q(sqft__range=(request.get("min_sqft"), request.get("max_sqft"))))
        if request.get("min_price") or request.get("max_price"):
            queryset = queryset.filter(Q(price__range=(request.get("min_price"), request.get("max_price"))))
        return queryset

    def get_initial(self):
        return {
            "location": self.request.GET.get("location", None),
            "category": self.request.GET.get("category", None),
            "look_for": self.request.GET.get("look_for", None),
            "min_sqft": self.request.GET.get("min_sqft", None),
            "max_sqft": self.request.GET.get("max_sqft", None),
            "min_price": self.request.GET.get("min_price", None),
            "max_price": self.request.GET.get("max_price", None),
            "sort_by": self.request.GET.get("sort_by", "pub_date"),
            "paginate_by": self.request.GET.get("paginate_by", "6"),
        }

property/templates/property/pagination.html
{% if is_paginated %}
{% with params=request.GET.urlencode %}
    <!-- Start pagiantion -->
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <a href="{% relative_url 1 'page' params %}" aria-label="First">
                    <span aria-hidden="true">First</span>
                </a>
            </li>
            <li>
                <a href="{% relative_url page_obj.previous_page_number 'page' params %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="active"><a href="{% relative_url num 'page' params %}">{{num}}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <li><a href="{% relative_url num 'page' params %}">{{num}}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a href="{% relative_url page_obj.next_page_number 'page' params %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span></a>
            <li>
                <a href="{% relative_url page_obj.paginator.num_pages 'page' params %}" aria-label="Last">
                    <span aria-hidden="true">Last</span>
                </a>
            </li>
        {%endif%}
    </ul>
    <!-- End of pagiantion -->
{%endwith%}
{% endif %}

property/templates/property/properties-detail.html
{% extends "base.html" %}
{% load static %}
{%load humanize%}

{% block title %}Property | Details{% endblock %}
{% block content %}
  <!-- Start Proerty header  -->

  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Properties Details</h2>
            <ol class="breadcrumb">
            <li><a href="#">HOME</a></li>            
            <li class="active">{{property.title}}</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section> 
  <!-- End Proerty header  -->

  <!-- Start Properties  -->
  <section id="aa-properties">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="aa-properties-content">            
            <!-- Start properties content body -->
            <div class="aa-properties-details">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{message}}
                </div>
              {% endfor %}
            {%endif%}
            {% if property.author == user%}
              <div>
                <a href="{% url 'users:update-property' property.id %}"><button type="button" class="btn btn-secondary">Update</button></a>
                <a href="{% url 'users:delete-property' property.id %}"<button type="button" class="btn btn-danger">Delete</button></a>
              </div>
              <hr>
            {%endif%}
             <div class="aa-properties-details-img">
              <img src="{{property.MainPhoto.url}}" alt="img">
              {% if property.photo_1 %}
                <img src="{{property.photo_1.url}}" alt="img">
              {% endif %}
              {% if property.photo_2 %}
                <img src="{{property.photo_2.url}}" alt="img">
              {% endif %}
              {% if property.photo_3 %}
                <img src="{{property.photo_3.url}}" alt="img">
              {% endif %}
              {% if property.photo_4 %}
                <img src="{{property.photo_4.url}}" alt="img">
              {% endif %}
              {% if property.photo_5 %}
                <img src="{{property.photo_5.url}}" alt="img">
              {% endif %}
              {% if property.photo_6 %}
                <img src="{{property.photo_6.url}}" alt="img">
              {% endif %}
             </div>
             <div class="aa-properties-info">
               <h2>{{property.title}}</h2>
               <h5>Posted at: {{property.pub_date|date:"Y b d"}}</h5>
               <h5>Views: {{property.views}}</h5>
               <span class="aa-price">Price: ${{property.price|intcomma}}</span>
               <h4>Address: {{property.address}}, {{property.city}}, {{property.state}}</h4>
               <p>{{property.description}}</p>
               <h4>Propery Features</h4>
               <ul>
                 <li>Area: {{property.sqft}} SQ FT</sup></var></li>
                 <li>{{property.bedrooms}} Bedroom</li>
                 <li>{{property.bathrooms}} Baths</li>
               </ul>
             </div>
             <!-- Properties social share -->
             <div class="aa-properties-social">
               <ul>
                 <li>Share</li>
                 <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                 <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                 <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                 <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
               </ul>
             </div>
             <!-- Nearby properties -->
             <div class="aa-nearby-properties">
               <div class="aa-title">
                 <h2>Nearby Properties</h2>
                 <span></span>
               </div>
               <div class="aa-nearby-properties-area">
                 <div class="row">
                  {% for near_p in nearby_properties %}
                   <div class="col-md-6">
                     <article class="aa-properties-item">
                        <a class="aa-properties-item-img" href="#">
                          <img alt="img" src="{{near_p.MainPhoto.url}}">
                        </a>
                        {% if near_p.get_property_status_display == "For Sale" %}
                        <div class="aa-tag for-sale">
                          {{near_p.get_property_status_display}}
                        </div>
                        {% elif near_p.get_property_status_display == "For Rent"%}
                        <div class="aa-tag for-rent">
                          {{near_p.get_property_status_display}}
                        </div>
                        {% else %}
                        <div class="aa-tag sold-out">
                          {{near_p.get_property_status_display}}
                        </div>
                        {% endif %}
                        <div class="aa-properties-item-content">
                          <div class="aa-properties-info">
                            <span>{{near_p.bedrooms}} Beds</span>
                            <span>{{near_p.bathrooms}} Baths</span>
                            <span>{{near_p.sqft}} SQ FT</span>
                            <span>City: {{near_p.city}}</span>
                          </div>
                          <div class="aa-properties-about">
                            <h3><a href="{% url 'property:Properties-Detail' near_p.id %}">{{near_p.title}}</a></h3>
                            <p>{{near_p.description|truncatewords:10}}</p>                      
                          </div>
                          <div class="aa-properties-detial">
                            <span class="aa-price">
                              ${{near_p.price|intcomma}}
                            </span>
                            <a class="aa-secondary-btn" href="{% url 'property:Properties-Detail' near_p.id %}">View Details</a>
                          </div>
                        </div>
                      </article>
                   </div>
                  {% endfor %}
                 </div>
               </div>

             </div>

            </div>           
          </div>
        </div>
        <!-- Start properties sidebar -->
        {% include 'property/sidebar.html' %}
        <!-- End properties sidebar -->
      </div>
    </div>
  </section>
  <!-- / Properties  -->
{% endblock %}

property/templates/property/properties-list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load template_tags %}

{% block title %}Home Property | Properties{% endblock title %}
{% block content %}
  <!-- Start Proerty header  -->
  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Properties Page</h2>
            <ol class="breadcrumb">
            <li><a href="">HOME</a></li>            
            <li class="active">PROPERTIES</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section> 
  <!-- End Proerty header  -->

  <!-- Start Properties  -->
  <section id="aa-properties">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="aa-properties-content">
            <!-- start properties content head -->
            <div class="aa-properties-content-head">              
              <div class="aa-properties-content-head-left">
                <form class="aa-sort-form" method="GET">
                  <label for="">Sort by</label>
                  {{form.sort_by}}
                </form>
                <form class="aa-show-form" method="GET">
                  <label for="">Show</label>
                  {{form.paginate_by}}
                </form>
              </div>
              <div class="aa-properties-content-head-right">
                <a id="aa-grid-properties" href="#"><span class="fa fa-th"></span></a>
                <a id="aa-list-properties" href="#"><span class="fa fa-list"></span></a>
              </div>            
            </div>
            <!-- Start properties content body -->
            <div class="aa-properties-content-body">
              <ul class="aa-properties-nav">
                {% for property in properties %}
                  <li>
                    <article class="aa-properties-item">
                      <a class="aa-properties-item-img" href="{{property.get_absolute_url}}">
                        <img alt="img" src="{{property.MainPhoto.url}}">
                      </a>
                      {% if property.get_property_status_display == "For Sale" %}
                        <div class="aa-tag for-sale">
                          {{property.get_property_status_display}}
                        </div>
                      {% endif %}
                      {% if property.get_property_status_display == "For Rent"%}
                        <div class="aa-tag for-rent">
                          {{property.get_property_status_display}}
                        </div>
                      {% endif %}
                      {% if property.get_property_status_display == "Sold Out" %}
                        <div class="aa-tag sold-out">
                          {{property.get_property_status_display}}
                        </div>
                      {% endif %}
                      <div class="aa-properties-item-content">
                        <div class="aa-properties-info">
                          <span>{{property.bedrooms}} Beds</span>
                          <span>{{property.bathrooms}} Baths</span>
                          <span>{{property.sqft}} SQ FT</span>
                          <span>City: {{property.city}}</span>
                        </div>
                        <div class="aa-properties-about">
                          <h3><a href="{{property.get_absolute_url}}">{{property.title}}</a></h3>
                          <p>{{property.description|truncatewords:20}}</p>                      
                        </div>
                        <div class="aa-properties-detial">
                          <span class="aa-price">
                            ${{property.price|intcomma}}
                          </span>
                          <a class="aa-secondary-btn" href="{{property.get_absolute_url}}">View Details</a>
                        </div>
                      </div>
                    </article>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <!-- Start properties content bottom -->
            <div class="aa-properties-content-bottom">
              <nav>
                {%include 'property/pagination.html'%}
              </nav>
            </div>
          </div>
        </div>
        <!-- Start properties sidebar -->
        {% include 'property/sidebar.html' %}
        <!-- End properties sidebar -->
      </div>
    </div>
  </section>
  <!-- / Properties  -->
{% endblock content%}