blog/urls.py
from django.urls import path
from . import views
from .api import viewsets as api_viewsets

app_name = "blog"

blog_list = api_viewsets.BlogAPI.as_view({"get": "list"})
blog_detail = api_viewsets.BlogAPI.as_view({"get": "retrieve", "post": "create"})

urlpatterns = [
    path("blogs", views.BlogList.as_view(), name="Blogs-List"),
    path("blogs/<int:pk>", views.BlogDetail.as_view(), name="Blog-Detail"),
    path("blogs/search", views.BlogSearch.as_view(), name="Blog-Search"),
    path(
        "blogs/categories/<slug:category>/",
        views.CategoryView.as_view(),
        name="Blog-Category",
    ),
    path("blogs/tags/<slug:tag>/", views.TagView.as_view(), name="Blog-Tag"),
    ######## API ########
    path("api/blogs/", blog_list, name="api_blog_list"),
    path("api/blogs/<int:pk>/", blog_detail, name="api_blog_detail"),
    path("api/blogs/search/", api_viewsets.BlogSearchAPI.as_view(), name="api_blog_search"),
    path("api/blogs/categories/", api_viewsets.CategoryAPI.as_view(), name="api_categories"),
    path("api/blogs/categories/<slug:category>/", api_viewsets.BlogsByCategoryAPI.as_view(), name="api_blog_category"),
    path("api/blogs/tags/", api_viewsets.TagAPI.as_view(), name="api_tags"),
    path("api/blogs/tags/<slug:tag>/", api_viewsets.BlogsByTagAPI.as_view(), name="api_blog_tag"),
]

home_property_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from contact.views import ContactView
from contact.api.viewsets import ContactAPI

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("property.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("users.api.urls", namespace="users_api")),
    path("", include("property.api.urls", namespace="property_api")),
    path("contact/", ContactView, name="contact"),
    path("api/contact/", ContactAPI.as_view(), name="api_contact"),
    path("accounts/", include("users.urls", namespace="users")),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "home_property_project.views.page_not_found_view"

blog/models.py
from django.db import models
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.urls import reverse

class Blog(models.Model):
    title = models.CharField(max_length=55, verbose_name='Title')
    author = models.ForeignKey(User, verbose_name='Author', on_delete = models.CASCADE, blank=False, null=False)
    category = models.ForeignKey("Category", related_name="blog", verbose_name='Category', on_delete=models.CASCADE, blank=True, null=True)
    tag = models.ManyToManyField("Tag", related_name="blogs", verbose_name='Tags', blank=True)
    image = models.ImageField(upload_to='blogs/', verbose_name='Image')
    content = RichTextField()
    slug = AutoSlugField(populate_from='title')
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:Blog-Detail', kwargs={"pk": self.pk})
    
    class Meta:
        ordering = ('-pub_date',)
    
class Category(models.Model):
    title = models.CharField(max_length=55, verbose_name='Title')
    slug = AutoSlugField(populate_from='title')
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:Blog-Category", kwargs={"category": self.slug})
    
    class Meta:
        verbose_name_plural = "Catrgories"
        
        
class Tag(models.Model):
    title = models.CharField(max_length=55, verbose_name='Title')
    slug = AutoSlugField(populate_from='title')
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:Blog-Tag", kwargs={"tag": self.slug})
    
    
class Comments(models.Model):
    blog = models.ForeignKey("Blog", verbose_name="Blog", on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=55, verbose_name="Name")
    email = models.EmailField(max_length=100, verbose_name="Email")
    comment = models.TextField(verbose_name="Comment")
    date = models.DateTimeField(auto_now_add=True, auto_now=False)
    
    def __str__(self):
        return self.email
    
    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

blog/forms.py
from django import forms
from .models import Comments

class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'style':'resize:none;'}))
    class Meta:
        model = Comments
        fields = ('name', 'email', 'comment')

blog/views.py
from django.shortcuts import redirect, get_list_or_404
from .models import Blog
from django.views.generic.edit import FormMixin
from .forms import CommentForm
from django.views.generic import ListView, DetailView
from django.db.models import Q


class BlogList(ListView):
    queryset = Blog.objects.all().select_related("author").prefetch_related("comments")
    template_name = "blog/blog_list.html"
    context_object_name = "blogs"
    ordering = "-pub_date"
    paginate_by = 6


class BlogDetail(DetailView, FormMixin):
    model = Blog
    template_name = "blog/blog_detail.html"
    context_object_name = "blog"
    form_class = CommentForm
    success_url = "/"

    def get_context_data(self, *args, **kwargs):
        context = super(BlogDetail, self).get_context_data(*args, **kwargs)
        context["related_posts"] = (
            Blog.objects.filter(category=self.object.category)
            .select_related("author")
            .prefetch_related("comments")
            .exclude(id=self.object.pk)[:2]
        )
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        self.object = self.get_object()
        new_comment.blog = self.object
        form.save()
        return redirect(self.object.get_absolute_url())

    def get_object(self, queryset=None):
        return Blog.objects.filter(pk=self.kwargs.get("pk")).select_related("author").prefetch_related("comments").first()


class BlogSearch(ListView):
    queryset = Blog.objects.all().select_related("author").prefetch_related("comments")
    template_name = "blog/blog_list.html"
    context_object_name = "blogs"
    ordering = "-pub_date"
    paginate_by = 6

    def get_queryset(self):
        search_for = self.request.GET.get("q")
        if search_for:
            return self.queryset.filter(Q(title__icontains=search_for) | Q(content__icontains=search_for))
        return self.queryset


class CategoryView(ListView):
    template_name = "blog/blog_list.html"
    context_object_name = "blogs"
    paginate_by = 6

    def get_queryset(self):
        return get_list_or_404(Blog.objects.select_related("author").prefetch_related("comments"), category__slug=self.kwargs["category"])


class TagView(ListView):
    template_name = "blog/blog_list.html"
    context_object_name = "blogs"
    paginate_by = 6

    def get_queryset(self):
        return get_list_or_404(Blog.objects.select_related("author").prefetch_related("comments"), tag__slug=self.kwargs["tag"])

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home Property | Blog{% endblock title %}

{% block content %}
  <!-- Start Proerty header  -->
  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Blog Details</h2>
            <ol class="breadcrumb">
            <li><a href="#">HOME</a></li>            
            <li class="active">Blog Details</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section> 
  <!-- End Proerty header  -->

  <!-- Start Blog  -->
  <section id="aa-blog">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-blog-area">
            <div class="row">
              <div class="col-md-8">
                <div class="aa-blog-content">
                  <div class="row">
                    <div class="col-md-12">
                      <article class="aa-blog-single aa-blog-details">
                        <figure class="aa-blog-img">
                          <a href="#"><img alt="img" src="{{blog.image.url}}"></a>
                          <span class="aa-date-tag">{{blog.pub_date|date:"Y b d"}}</span>
                        </figure>
                        <div class="aa-blog-single-content">
                          <h2>{{blog.title}}</h2>
                          <div class="aa-blog-single-bottom">
                            <a class="aa-blog-author" href="#"><i class="fa fa-user"></i>{{blog.author}}</a>
                            <a class="aa-blog-comments" href="#"><i class="fa fa-comment-o"> {{blog.comments.count}}</i></a>
                          </div>
                          <p>{{blog.content|safe}}</p> 
                        </div>                   
                      </article>
                    </div>
                    <!-- Post tags -->
                    <div class="col-md-12">
                      <div class="aa-blog-post-tag">
                        <ul>
                          <li>TAGS:</li>
                          {% for tag in tags %}
                          <li><a href="{% url 'blog:Blog-Tag' tag.slug %}">{{tag}},</a></li> 
                          {% endfor %}                        
                        </ul>
                      </div>
                    </div>
                    <!-- Social Share -->
                    <div class="col-md-12">
                      <div class="aa-properties-social">
                       <ul>
                         <li>Share</li>
                         <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                         <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                         <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                         <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                       </ul>
                     </div>
                    </div>
                    <!-- post navigation -->
                    <div class="col-md-12">
                      <div class="aa-blog-navigation">
                        <div class="aa-blog-pagination-left">
                          <a href="{{blog.get_previous_by_pub_date.get_absolute_url}}" class="aa-prev">
                            <span class="fa fa-angle-double-left">                            
                            </span>
                            PREV
                          </a>
                        </div>
                        <div class="aa-blog-pagination-right">
                          <a href="{{blog.get_next_by_pub_date.get_absolute_url}}" class="aa-next">
                            NEXT
                            <span class="fa fa-angle-double-right">                            
                            </span>
                          </a>                          
                        </div>
                      </div>
                    </div>
                    <!-- Related blog post -->
                    <div class="col-md-12">
                      <div class="aa-blog-related-post">
                        <div class="aa-title">
                          <h2>Related Post</h2>
                          <span></span>
                        </div>
                        <div class="aa-blog-related-post-area">
                          <div class="row">
                          {% for post in related_posts %}
                            <div class="col-md-6 col-sm-6">
                              <article class="aa-blog-single">
                                <figure class="aa-blog-img">
                                  <a href="#"><img src="{{post.image.url}}" alt="img"></a>
                                  <span class="aa-date-tag">{{post.pub_date|date:"Y b d"}}</span>
                                </figure>
                                <div class="aa-blog-single-content">
                                  <h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                                  <p>{{post.content|safe|truncatewords:20}}</p>
                                  <div class="aa-blog-single-bottom">
                                    <a href="#" class="aa-blog-author"><i class="fa fa-user"></i> {{post.author}}</a>
                                    <a href="#" class="aa-blog-comments"><i class="fa fa-comment-o"></i>{{post.comments.count}}</a>
                                  </div>
                                </div>                   
                              </article>
                            </div>
                          {% endfor %}
                          </div>
                        </div>
                      </div>
                    </div>  
                    <!-- comment threats -->
                    <div class="col-md-12">
                      <div class="aa-comments-area">
                        <h3>{{blog.comments.all.count}} Comments</h3>
                        <div class="comments">
                          <ul class="commentlist">
                          {% for comment in blog.comments.all %}
                            <li>
                              <div class="media">
                                <div class="media-left">    
                                    <img alt="img" src="{%static 'img/default.jpg'%}" class="media-object news-img">      
                                </div>
                                <div class="media-body">
                                 <h4 class="author-name">{{comment.name}}</h4>
                                 <span class="comments-date"> {{comment.date|date:"Y b d"}}</span>
                                 <p>{{comment.comment}}</p>
                                </div>
                              </div>
                            </li>
                          {% endfor %}
                          </ul>
                          <!-- comments pagination -->
                          <nav>
                            <ul class="pagination comments-pagination">
                              <li>
                                <a aria-label="Previous" href="#">
                                  <span aria-hidden="true">«</span>
                                </a>
                              </li>
                              <li><a href="#">1</a></li>
                              <li><a href="#">2</a></li>
                              <li><a href="#">3</a></li>
                              <li><a href="#">4</a></li>
                              <li><a href="#">5</a></li>
                              <li>
                                <a aria-label="Next" href="#">
                                  <span aria-hidden="true">»</span>
                                </a>
                              </li>
                            </ul>
                          </nav>
                        </div>
                      </div>
                    </div>   
                    <!-- Respond box -->
                    <div class="col-md-12">
                      <div id="respond">
                        <h3 class="reply-title">Leave a Comment</h3>
                        <form id="commentform" method="POST">
                          {% csrf_token %}
                          <p class="comment-notes">
                            Your email address will not be published. Required fields are marked <span class="required">*</span>
                          </p>
                          {{form.as_p}}
                          {% comment %} <p class="comment-form-author">
                            <label for="author">Name <span class="required">*</span></label>
                            <input type="text" required="required" size="30" value="" name="author">
                          </p>
                          <p class="comment-form-email">
                            <label for="email">Email <span class="required">*</span></label>
                            <input type="email" required="required" aria-required="true" value="" name="email">
                          </p>
                          <p class="comment-form-comment">
                            <label for="comment">Comment</label>
                            <textarea required="required" aria-required="true" rows="8" cols="45" name="comment"></textarea>
                          </p>
                          <p class="form-allowed-tags">
                            You may use these <abbr title="HyperText Markup Language">HTML</abbr> tags and attributes:  <code>&lt;a href="" title=""&gt; &lt;abbr title=""&gt; &lt;acronym title=""&gt; &lt;b&gt; &lt;blockquote cite=""&gt; &lt;cite&gt; &lt;code&gt; &lt;del datetime=""&gt; &lt;em&gt; &lt;i&gt; &lt;q cite=""&gt; &lt;s&gt; &lt;strike&gt; &lt;strong&gt; </code>
                          </p> {% endcomment %}
                          <p class="form-submit">
                            <input type="submit" value="Post Comment" class="aa-browse-btn" name="submit">
                          </p>        
                        </form>
                      </div>
                    </div>
                  </div>                                   
                </div>
              </div>
              <!-- Start blog sidebar -->
              {% include 'blog/sidebar.html' %}
              <!-- End blog sidebar -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- / Blog  -->
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home Property | Blogs{% endblock title %}
{% block content %}

  <!-- Start Proerty header  -->
  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Blog Page</h2>
            <ol class="breadcrumb">
            <li><a href="#">HOME</a></li>            
            <li class="active">Blog</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section> 
  <!-- End Proerty header  -->

  <!-- Start Blog  -->
  <section id="aa-blog">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-blog-area">
            <div class="row">
              <div class="col-md-8">
                <div class="aa-blog-content">
                  <div class="row">
                  {% for blog in blogs %}
                    <div class="col-md-6 col-sm-6">
                      <article class="aa-blog-single">
                        <figure class="aa-blog-img">
                          <a href="{{blog.get_absolute_url}}"><img alt="img" src="{{blog.image.url}}"></a>
                          <span class="aa-date-tag">{{blog.pub_date|date:"Y b d"}}</span>
                        </figure>
                        <div class="aa-blog-single-content">
                          <h3><a href="{% url 'blog:Blog-Detail' blog.id %}">{{blog.title}}</a></h3>
                          <p>{{blog.content|safe|truncatewords:30}}</p>
                          <div class="aa-blog-single-bottom">
                            <a class="aa-blog-author" href="#"><i class="fa fa-user"></i> {{blog.author}}</a>
                            <a class="aa-blog-comments" href="#"><i class="fa fa-comment-o"></i>{{blog.comments.count}}</a>
                          </div>
                        </div>                   
                      </article>
                    </div>
                  {%endfor%}
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="aa-properties-content-bottom">
                        <nav>
                          {%include 'property/pagination.html'%}
                        </nav>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Start blog sidebar -->
              {% include "blog/sidebar.html"%}
              <!-- End blog sidebar -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- / Blog  -->

{% endblock content %}

blog/templates/blog/sidebar.html
{%load static%}
<div class="col-md-4">
    <aside class="aa-blog-sidebar">
        <!-- Start single sidebar -->
        <div class="aa-blog-sidebar-single">
            <form action="{% url 'blog:Blog-Search' %}" method="GET">
                <div class="aa-blog-search">
                <input class="aa-search-text" type="text" name="q" placeholder="Search...">
                <button class="aa-search-submit" type="submit">
                    <i class="fa fa-search"></i>
                </button>
                </div>
            </form>
        </div>
        <!-- Start single sidebar -->
        <div class="aa-blog-sidebar-single">
            <h3>Categories</h3>
            <ul class="aa-blog-catg">
            {% for category in categories %}
                <li><a href="{{category.get_absolute_url}}">{{category.title}}</a><span>{{category.num_blogs}}</span></li>
            {% endfor %}
            </ul>
        </div>
        <!-- Start single sidebar -->
        <div class="aa-blog-sidebar-single">
            <h3>Tags</h3>
            <div class="tag-cloud">
            {% for tag in tags %}
                <a href="{{tag.get_absolute_url}}">{{tag.title}}</a>
            {% endfor %}
            </div>                    
        </div>
        <!-- Start single sidebar -->
        <div class="aa-blog-sidebar-single">
            <h3>Recent Post</h3>
            <div class="aa-blog-recent-post">
            {% for post in recent_posts %}
                <div class="media">
                    <div class="media-left">
                        <a href="{{post.get_absolute_url}}">
                            <img alt="img" src="{{post.image.url}}" class="media-object">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>
                        <p>{{post.content|truncatewords:10|safe}}</p>                
                        <span>{{post.pub_date|date:"Y b d"}}</span>
                    </div>              
                </div>
            {%endfor%}
            </div>                    
        </div>
        <!-- Start single sidebar -->
        <div class="aa-blog-sidebar-single">
            <div class="aa-banner-ads">
                <a href="#">
                <img src="{%static 'img/banner-ads.jpg'%}" alt="banner img">
                </a>
            </div>                    
        </div>
    </aside>
</div>