blog/urls.py
from django.urls import path
from . import views
from .api import viewsets as api_viewsets

app_name = "blog"

blog_list = api_viewsets.BlogAPI.as_view({"get": "list"})
blog_detail = api_viewsets.BlogAPI.as_view({"get": "retrieve", "post": "create"})

urlpatterns = [
    path("blogs", views.BlogList.as_view(), name="Blogs-List"),
    path("blogs/<int:pk>", views.BlogDetail.as_view(), name="Blog-Detail"),
    path("blogs/search", views.BlogSearch.as_view(), name="Blog-Search"),
    path(
        "blogs/categories/<slug:category>/",
        views.CategoryView.as_view(),
        name="Blog-Category",
    ),
    path("blogs/tags/<slug:tag>/", views.TagView.as_view(), name="Blog-Tag"),
    ######## API ########
    path("api/blogs/", blog_list, name="api_blog_list"),
    path("api/blogs/<int:pk>/", blog_detail, name="api_blog_detail"),
    path("api/blogs/search/", api_viewsets.BlogSearchAPI.as_view(), name="api_blog_search"),
    path("api/blogs/categories/", api_viewsets.CategoryAPI.as_view(), name="api_categories"),
    path("api/blogs/categories/<slug:category>/", api_viewsets.BlogsByCategoryAPI.as_view(), name="api_blog_category"),
    path("api/blogs/tags/", api_viewsets.TagAPI.as_view(), name="api_tags"),
    path("api/blogs/tags/<slug:tag>/", api_viewsets.BlogsByTagAPI.as_view(), name="api_blog_tag"),
]

home_property_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from contact.views import ContactView
from contact.api.viewsets import ContactAPI

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("property.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("users.api.urls", namespace="users_api")),
    path("", include("property.api.urls", namespace="property_api")),
    path("contact/", ContactView, name="contact"),
    path("api/contact/", ContactAPI.as_view(), name="api_contact"),
    path("accounts/", include("users.urls", namespace="users")),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "home_property_project.views.page_not_found_view"

property/urls.py
from django.urls import path
from . import views

app_name = "property"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="Home-Page"),
    path("properties/", views.PropertiesList.as_view(), name="Properties-List"),
    path("properties/<int:pk>/", views.PropertyDetailView.as_view(), name="Properties-Detail"),
    path("properties/users/<str:username>/", views.UserPropertiesListView.as_view(), name="user-properties"),
    path("properties/search/", views.SearchView.as_view(), name="Search"),
]

users/api/urls.py
from django.urls import path
from . import viewsets as api_viewsets

app_name = "users_api"

urlpatterns = [
    path("api/login/", api_viewsets.LoginAPI.as_view(), name="api_login"),
    path("api/register/", api_viewsets.RegisterAPI.as_view(), name="api_register"),
    path("api/profile/", api_viewsets.ProfileAPI.as_view(), name="api_profile"),
    path("api/user/", api_viewsets.UserAPI.as_view(), name="api_user"),
    path("api/change-password/", api_viewsets.ChangePasswordAPI.as_view(), name="api_change_password"),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import PasswordResetForm


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path("login/", views.LoginView.as_view(), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<str:username>', views.profile, name='profile'),
    path("property/new/", views.PropertyCreateView.as_view(), name = "create-property"),
    path("change-password/", views.ChangePasswordView.as_view(), name = "change-password"),
    path('post/<int:pk>/update/', views.PropertyUpdateView.as_view(), name='property-update'),
    path("property/<int:pk>/update/", views.PropertyUpdateView.as_view(), name = "update-property"),
    path("property/<int:pk>/delete/", views.PropertyDeleteView.as_view(), name = "delete-property"),
    # password reset
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        form_class=PasswordResetForm,
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy("users:password_reset_complete")),
        name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f"{self.user.username}'s profile"
    
    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordResetForm as PasswordResetFormCore
from .models import Profile
from property.models import Property
from .tasks import send_create_property_email_task, send_password_reset_email_task


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]


FIELDS = [
    "title",
    "property_status",
    "address",
    "state",
    "city",
    "description",
    "category",
    "price",
    "bedrooms",
    "bathrooms",
    "garage",
    "sqft",
    "MainPhoto",
    "photo_1",
    "photo_2",
    "photo_3",
    "photo_4",
    "photo_5",
    "photo_6",
]


class CreatePropertyForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "1234 Main St"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"style": "resize:none;"}))
    state = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "e.g Califronia"}))
    city = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "e.g Los Angles"}))
    
    def send_email(self, email: str):
        return send_create_property_email_task.delay(
            self.cleaned_data["title"],
            self.instance.get_property_status_display(),
            self.cleaned_data["description"],
            [email])

    class Meta:
        model = Property
        exclude = ["author", "views", "status"]


class PasswordResetForm(PasswordResetFormCore):
    email = forms.EmailField(max_length=254, widget=forms.EmailInput(
        attrs={"autocomplete": "email"}
    ))

    def send_mail(
        self,
        subject_template_name,
        email_template_name,
        context,
        from_email,
        to_email,
        html_email_template_name=None,
    ):
        """
        This method is inherating Django's core `send_mail` method from `PasswordResetForm` class
        """
        context['user'] = context['user'].id
        send_password_reset_email_task.delay(
            subject_template_name=subject_template_name, 
            email_template_name=email_template_name,
            context=context,
            from_email=from_email,
            to_email=to_email,
            html_email_template_name=html_email_template_name
        )

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, CreatePropertyForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from property.models import Property
from django.views.generic import UpdateView, DeleteView, CreateView
from django.contrib.auth import views as auth_views
from django.views.generic import FormView
from django.urls import reverse_lazy


FIELDS = [
    "title",
    "property_status",
    "address",
    "state",
    "city",
    "description",
    "category",
    "price",
    "bedrooms",
    "bathrooms",
    "garage",
    "sqft",
    "MainPhoto",
    "photo_1",
    "photo_2",
    "photo_3",
    "photo_4",
    "photo_5",
    "photo_6",
]


class RegisterView(SuccessMessageMixin, FormView):
    template_name = "users/register.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")
    success_message = "Your account has been created! You are now able to log in"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("users:profile", request.user.username)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    template_name = "users/login.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse("users:profile", args=[self.request.user.username])


@login_required()
def profile(request, username):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated")
            return redirect("users:profile", request.user.username)
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        "u_form": u_form,
        "p_form": p_form,
    }
    return render(request, "users/profile.html", context)


class ChangePasswordView(LoginRequiredMixin, SuccessMessageMixin, auth_views.PasswordChangeView):
    template_name = "users/change_password.html"
    form_class = PasswordChangeForm
    success_message = "Your password has been changed!"

    def get_success_url(self):
        return reverse("users:profile", args=[self.request.user.username])


class PropertyCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "users/property-create-update.html"
    form_class = CreatePropertyForm
    success_message = "Your property has been listed!"

    def form_valid(self, form: CreatePropertyForm):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        form.send_email(self.request.user.email)
        return response

    def get_success_url(self):
        return reverse("users:profile", args=[self.request.user.username])


class PropertyUpdateView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, UpdateView):
    model = Property
    template_name = "users/property-create-update.html"
    fields = FIELDS
    success_message = "Your property has been updated successfully."

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        property = self.get_object()
        if self.request.user == property.author:
            return True
        return False


class PropertyDeleteView(LoginRequiredMixin, SuccessMessageMixin, UserPassesTestMixin, DeleteView):
    model = Property
    template_name = "users/property-delete.html"
    success_message = "Your property has been deleted successfully."

    def test_func(self):
        property = self.get_object()
        if self.request.user == property.author:
            return True
        return False

    def get_success_url(self):
        return reverse("users:profile", args=[self.request.user.username])

users/templates/users/change_password.html
{%extends 'base.html'%}
{%load static %}
{%load crispy_forms_tags%}
{%block title %}Home Property | Reset Password{%endblock title%}
{%block content%}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-property-header-inner">
                    <h2>User Dashboard</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Users</a></li>            
                        <li class="active">Change Password</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    </section> 
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}">
                                        {{message}}
                                    </div>
                                {% endfor %}
                            {%endif%}
                                <div class="content-section">
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-outline-info" type="submit">Change Password</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/login.html
{%extends 'login-register-base.html'%}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Sign in{%endblock title%}
{% block content %}
  <section id="aa-signin">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-signin-area">
            <div class="aa-signin-form">
              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{message}}
                  </div>
                {% endfor %}
              {%endif%}
              <div class="aa-signin-form-title">
                <a class="aa-property-home" href="{%url 'property:Home-Page'%}">Property Home</a>
                <h4>Sign in to your account</h4>
              </div>
              <form class="contactform" method="POST">
              {%csrf_token%}                                               
                {{form|crispy}}
                <div class="aa-single-submit">
                  <input type="submit" value="Sign in" class="aa-browse-btn" name="submit">
                  <p>Don't Have A Account Yet? <a href="{%url 'users:register'%}">CREATE NOW!</a></p>
                  <p>Forgot Password? <a href="{%url 'users:password_reset'%}">Reset Password</a></p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{%endblock content%}

users/templates/users/logout.html
{%extends 'base.html' %}
{%load static %}
{% load crispy_forms_tags %}
{%block title%}Home Property | Profile{%endblock title%}
{%block content %}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-property-header-inner">
                        <h2>User Dashboard</h2>
                        <ol class="breadcrumb">
                            <li><a href="{%url 'users:login'%}">Users</a></li>        
                            <li class="active">Logged out</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section> 
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                                <h2>You have been logged out</h2>
                                <div class="border-top pt-3">
                                    <small class="text-muted">
                                        <a href="{% url 'users:login' %}">Log In Again</a>
                                    </small>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/password_reset.html
{%extends 'base.html'%}
{%load static %}
{%load crispy_forms_tags%}
{%block title %}Home Property | Reset Password{%endblock title%}
{%block content%}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-property-header-inner">
                    <h2>User Dashboard</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Users</a></li>            
                        <li class="active">Reset Password</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    </section> 
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="content-section">
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/password_reset_complete.html
{%extends 'base.html'%}
{%load static %}
{%load crispy_forms_tags%}
{%block title %}Home Property | Reset Password{%endblock title%}
{%block content%}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-property-header-inner">
                    <h2>User Dashboard</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Users</a></li>            
                        <li class="active">Reset Password</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    </section> 
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="content-section">
                                    <div class="alert alert-info">
                                        Your password has been set.
                                    </div>
                                    <a href="{% url 'users:login' %}">Sign In Here</a>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/password_reset_confirm.html
{%extends 'base.html'%}
{%load static %}
{%load crispy_forms_tags%}
{%block title %}Home Property | Reset Password{%endblock title%}
{%block content%}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-property-header-inner">
                    <h2>User Dashboard</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Users</a></li>            
                        <li class="active">Reset Password</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    </section> 
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="content-section">
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            <legend class="border-bottom mb-4">Reset Password</legend>
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-outline-info" type="submit">Reset Password</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/password_reset_done.html
{%extends 'base.html'%}
{%load static %}
{%load crispy_forms_tags%}
{%block title %}Home Property | Reset Password{%endblock title%}
{%block content%}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-property-header-inner">
                    <h2>User Dashboard</h2>
                    <ol class="breadcrumb">
                        <li><a href="#">Users</a></li>            
                        <li class="active">Reset Password</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    </section> 
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="content-section">
                                    <div class="alert alert-info">
                                        An email has been sent with instructions to reset your password
                                    </div>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/password_reset_email.html
{% autoescape off %}
Hi {{ user.get_username }},

You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Your username, in case you've forgotten: {{ user.get_username }}

Thanks for using our site!

The {{ site_name }} team
{% endautoescape %}

users/templates/users/profile-sidebar.html
<div class="col-md-4">
    <aside class="aa-blog-sidebar">
        <div class="aa-blog-sidebar-single">
            <h3>Panel</h3>
            <ul class="aa-blog-catg">
            {%if user.is_authenticated %}
                <li><a href="{%url 'users:profile' user.username%}">Profile</a></li>
                <li><a href="{%url 'property:user-properties' user.username%}">Your Properties</a></li>
                <li><a href="{%url 'users:change-password'%}">Change Password</a></li>
                <li><a href="{%url 'users:create-property'%}">Add Property</a></li>
            {%else%}
                <li><a href="{%url 'users:login'%}">Login</a></li>
                <li><a href="{%url 'users:register'%}">Register</a></li>
            {%endif%}
            </ul>
        </div>
    </aside>
</div>

users/templates/users/property-delete.html
{% extends 'base.html'%}
{%load static%}
{%block title%}Home Property | Delete Property{%endblock%}
{%block content%}
    <!-- Start Proerty header  -->
    <section id="aa-property-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-property-header-inner">
                        <h2>User Dashboard</h2>
                        <ol class="breadcrumb">
                            <li><a href="#">Users</a></li>            
                            <li class="active">Dashboard</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Proerty header  -->
    <section id="aa-blog">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-blog-area">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="content-section">
                                    <form method="POST" action="">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            <legend class="border-bottom mb-4">Delete Post</legend>
                                            <h3>Are you sure you want to delete the post "{{ object.title }}"</h3>
                                        </fieldset>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-danger">Yes, Delete</button>
                                            <a href="{% url 'property:Properties-Detail' object.id %}"<button type="button" class="btn btn-secondary">Cancel</button></a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            {%include 'users/profile-sidebar.html'%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

users/templates/users/register.html
{%extends 'login-register-base.html'%}
{% load static %}
{% load crispy_forms_tags %}

{%block title%}Register{%endblock title%}
{%block content%}
  <section id="aa-signin">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-signin-area">
            <div class="aa-signin-form">
              <div class="aa-signin-form-title">
                <a class="aa-property-home" href="{%url 'property:Home-Page'%}">Property Home</a>
                <h4>Create your account and Stay with us</h4>
              </div>
              <form class="contactform" method="POST">                                                 
                {%csrf_token%}
                {{form|crispy}}
                <div class="aa-single-submit">
                  <input type="submit" value="Create Account" name="submit">                    
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{%endblock content%}