blog/urls.py
from django.urls import path
from . import views
from .api import viewsets as api_viewsets

app_name = "blog"

blog_list = api_viewsets.BlogAPI.as_view({"get": "list"})
blog_detail = api_viewsets.BlogAPI.as_view({"get": "retrieve", "post": "create"})

urlpatterns = [
    path("blogs", views.BlogList.as_view(), name="Blogs-List"),
    path("blogs/<int:pk>", views.BlogDetail.as_view(), name="Blog-Detail"),
    path("blogs/search", views.BlogSearch.as_view(), name="Blog-Search"),
    path(
        "blogs/categories/<slug:category>/",
        views.CategoryView.as_view(),
        name="Blog-Category",
    ),
    path("blogs/tags/<slug:tag>/", views.TagView.as_view(), name="Blog-Tag"),
    ######## API ########
    path("api/blogs/", blog_list, name="api_blog_list"),
    path("api/blogs/<int:pk>/", blog_detail, name="api_blog_detail"),
    path("api/blogs/search/", api_viewsets.BlogSearchAPI.as_view(), name="api_blog_search"),
    path("api/blogs/categories/", api_viewsets.CategoryAPI.as_view(), name="api_categories"),
    path("api/blogs/categories/<slug:category>/", api_viewsets.BlogsByCategoryAPI.as_view(), name="api_blog_category"),
    path("api/blogs/tags/", api_viewsets.TagAPI.as_view(), name="api_tags"),
    path("api/blogs/tags/<slug:tag>/", api_viewsets.BlogsByTagAPI.as_view(), name="api_blog_tag"),
]

home_property_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from contact.views import ContactView
from contact.api.viewsets import ContactAPI

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("property.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("", include("users.api.urls", namespace="users_api")),
    path("", include("property.api.urls", namespace="property_api")),
    path("contact/", ContactView, name="contact"),
    path("api/contact/", ContactAPI.as_view(), name="api_contact"),
    path("accounts/", include("users.urls", namespace="users")),
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = "home_property_project.views.page_not_found_view"

property/urls.py
from django.urls import path
from . import views

app_name = "property"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="Home-Page"),
    path("properties/", views.PropertiesList.as_view(), name="Properties-List"),
    path("properties/<int:pk>/", views.PropertyDetailView.as_view(), name="Properties-Detail"),
    path("properties/users/<str:username>/", views.UserPropertiesListView.as_view(), name="user-properties"),
    path("properties/search/", views.SearchView.as_view(), name="Search"),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import PasswordResetForm


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path("login/", views.LoginView.as_view(), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<str:username>', views.profile, name='profile'),
    path("property/new/", views.PropertyCreateView.as_view(), name = "create-property"),
    path("change-password/", views.ChangePasswordView.as_view(), name = "change-password"),
    path('post/<int:pk>/update/', views.PropertyUpdateView.as_view(), name='property-update'),
    path("property/<int:pk>/update/", views.PropertyUpdateView.as_view(), name = "update-property"),
    path("property/<int:pk>/delete/", views.PropertyDeleteView.as_view(), name = "delete-property"),
    # password reset
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        form_class=PasswordResetForm,
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy("users:password_reset_complete")),
        name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    email = models.EmailField(max_length=255, blank=False, null=False)
    subject = models.CharField(max_length=255, null=False, blank=False)
    message = models.TextField(blank=False)
    date = models.DateField(auto_now_add=True, auto_now=False)
    
    def __str__(self):
        return self.email

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget = forms.Textarea)

contact/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .forms import ContactForm
from .models import Contact
from django.contrib import messages

def ContactView(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data['name']
            new_email = form.cleaned_data['email']
            new_subject = form.cleaned_data['subject']
            new_message = form.cleaned_data['message']
            
            new_contact = Contact(name=new_name, email=new_email, subject=new_subject, message=new_message)
            new_contact.save()
            messages.success(request, f'Your message has been sent successfully.')
            return HttpResponseRedirect(reverse("contact"))
        
    return render(request, 'contact.html')

templates/base.html
{% load static %}
{%load humanize%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>{% block title %}
      {{ title|default:"Untitled Page" }}
      {% endblock title %}
    </title>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

    <!-- Font awesome -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">   
    <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/nouislider.css' %}">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" type="text/css" media="screen" /> 
    <!-- Theme color -->
    <link id="switcher" href="{% static 'css/theme-color/default-theme.css' %}" rel="stylesheet">     

    <!-- Main style sheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">    

   
    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>    
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body class="aa-price-range">  
  <!-- Pre Loader -->
  <div id="aa-preloader-area">
    <div class="pulse"></div>
  </div>
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-angle-double-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->

  <!-- Start header section -->
  <header id="aa-header">  
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-header-area">
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-left">
                  <div class="powered">
                   <a href="https://mountsol.com/" target="_blank" style="color: #fff;float: left;font-size: 15px;font-weight: 800;">Powered By MountSol</a> </div>
                  <div class="aa-telephone-no">
                    <span class="fa fa-phone"></span>
                    1-900-523-3564
                  </div>
                  <div class="aa-email hidden-xs">
                    <span class="fa fa-envelope-o"></span> usman@mountsol.com
                  </div>
                </div>              
              </div>
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-right">
                {%if user.is_authenticated%}
                  <a href="{%url 'users:profile' user.username%}" class="aa-register">{{user.get_username}}</a>
                  <a href="{%url 'users:logout'%}" class="aa-login">Log out</a>
                {%else%}
                  <a href="{%url 'users:register'%}" class="aa-register">Register</a>
                  <a href="{%url 'users:login'%}" class="aa-login">Login</a>
                {%endif%}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End header section -->

  <!-- Start menu section -->
  <section id="aa-menu-area">
    <nav class="navbar navbar-default main-navbar" role="navigation">  
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->                                               
          <!-- Text based logo -->
           <a class="navbar-brand aa-logo" href="{% url 'property:Home-Page' %}"> Home <span>Property</span></a>
           <!-- Image based logo -->
           <!-- <a class="navbar-brand aa-logo-img" href="index.html"><img src="img/logo.png" alt="logo"></a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav navbar-right aa-main-nav">
            <li class="{% if request.resolver_match.url_name == "property:Home-Page" %}active{% endif %}"><a href="{% url 'property:Home-Page' %}">HOME</a></li>
            <li class="{% if request.resolver_match.url_name == "property:Properties-List" %}active{% endif %}"><a href="{% url 'property:Properties-List'%}">PROPERTIES</a></li>                                       
            <li class="{% if request.resolver_match.url_name == "blog:Blogs-List" %}active{% endif %}"><a href="{% url 'blog:Blogs-List' %}">BLOGS</a></li>
            <li class="{% if request.resolver_match.url_name == "contact" %}active{% endif %}"><a href="{%url 'contact'%}">CONTACT</a></li>
          </ul>                            
        </div><!--/.nav-collapse -->       
      </div>          
    </nav> 
  </section>
  <!-- End menu section -->


  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer id="aa-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <div class="aa-footer-area">
          <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="aa-footer-left">
               <p>Designed by <a rel="nofollow" href="http://www.mountsol.com/">Mountsol.com</a></p>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="aa-footer-middle">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
              </div>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
              <div class="aa-footer-right">
                <a href="{% url 'property:Home-Page' %}">Home</a>
                <a href="#">Support</a>
                <a href="#">License</a>
                <a href="#">FAQ</a>
                <a href="#">Privacy & Term</a>
              </div>
            </div>            
          </div>
        </div>
      </div>
      </div>
    </div>
  </footer>
  <!-- / Footer -->

 
  
  <!-- jQuery library -->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
  <script src="{% static 'js/jquery.min.js' %}"></script>   
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'js/bootstrap.js' %}"></script>   
  <!-- slick slider -->
  <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>
  <!-- Price picker slider -->
  <script type="text/javascript" src="{% static 'js/nouislider.js' %}"></script>
   <!-- mixit slider -->
  <script type="text/javascript" src="{% static 'js/jquery.mixitup.js' %}"></script>
  <!-- Add fancyBox -->        
  <script type="text/javascript" src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
  <!-- Humanize package-->
  <script type="text/javascript" src="{% static 'js/humanize.js' %}"></script>
  <!-- Custom js -->
  <script src="{% static 'js/custom.js' %}"></script> 

  </body>
</html>

templates/contact.html
{%extends 'base.html' %}
{%load static %}

{% block title%}Home Property | Contact{%endblock%}
{%block content%}
  <!-- Start Proerty header  -->

  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Contact</h2>
            <ol class="breadcrumb">
            <li><a href="#">HOME</a></li>            
            <li class="active">Contact</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section> 
  <!-- End Proerty header  -->

 <section id="aa-contact">
   <div class="container">
     <div class="row">
       <div class="col-md-12">
          <div class="aa-contact-area">
            <div class="aa-contact-top">
              {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{message}}
                  </div>
                {% endfor %}
              {%endif%}
              <div class="aa-contact-top-left">
                <iframe width="100%" height="450" frameborder="0" allowfullscreen="" style="border:0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6851.201919469417!2d-86.11773906635584!3d33.47324776828677!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x888bdb60cc49c571%3A0x40451ca6baf275c7!2s36008+AL-77%2C+Talladega%2C+AL+35160%2C+USA!5e0!3m2!1sbn!2sbd!4v1460452919256"></iframe>
              </div>
              <div class="aa-contact-top-right">
                <h2>Contact</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae placeat aspernatur aperiam, quisquam voluptas enim tempore ab itaque nam modi eos corrupti distinctio nobis labore dolorum quae tenetur. Sapiente, sequi.</p>
                <ul class="contact-info-list">
                  <li> <i class="fa fa-phone"></i> 1-700-564-6321</li>
                  <li> <i class="fa fa-envelope-o"></i> info@homeproperty.com</li>
                  <li> <i class="fa fa-map-marker"></i> 36008 AL-77, Talladega, AL 35160, USA</li>
                </ul>
              </div>
            </div>
            <div class="aa-contact-bottom">
              <div class="aa-title">
                <h2>Send Your Message</h2>
                <span></span>
                <p>Your email address will not be published. Required fields are marked <strong class="required">*</strong></p>
              </div>
              <div class="aa-contact-form">
                <form class="contactform" method='POST'> 
                {%csrf_token%}                 
                  <p class="comment-form-author">
                    <label for="author">Name <span class="required">*</span></label>
                    <input type="text" name="name" value="" size="30" required="required">
                  </p>
                  <p class="comment-form-email">
                    <label for="email">Email <span class="required">*</span></label>
                    <input type="email" name="email" value="" aria-required="true" required="required">
                  </p>
                  <p class="comment-form-url">
                    <label for="subject">Subject</label>
                    <input type="text" name="subject" required="required"> 
                  </p>
                  <p class="comment-form-comment">
                    <label for="comment">Message</label>
                    <textarea name="message" cols="45" rows="8" aria-required="true" required="required" style="resize:none"></textarea>
                  </p>                
                  <p class="form-submit">
                    <input type="submit" name="submit" class="aa-browse-btn" value="Send Message">
                  </p>        
                </form>
              </div>
            </div>
          </div>
       </div>
     </div>
   </div>
 </section>
{%endblock %}

templates/login-register-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <title>Home Property | {% block title %}
      {{ title|default:"Untitled Page" }}
      {% endblock title %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    
    
    <!-- Font awesome -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">   
    <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/nouislider.css' %}">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" type="text/css" media="screen" /> 
    <!-- Theme color -->
    <link id="switcher" href="{% static 'css/theme-color/default-theme.css' %}" rel="stylesheet">     

    <!-- Main style sheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">    

   
    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>    
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  

  </head>
  <body>

  {% block content %}
  {% endblock content %}

  <!-- jQuery library -->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
  <script src="{% static 'js/jquery.min.js' %}"></script>   
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'js/bootstrap.js' %}"></script>   
  <!-- slick slider -->
  <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>
  <!-- Price picker slider -->
  <script type="text/javascript" src="{% static 'js/nouislider.js' %}"></script>
   <!-- mixit slider -->
  <script type="text/javascript" src="{% static 'js/jquery.mixitup.js' %}"></script>
  <!-- Add fancyBox -->        
  <script type="text/javascript" src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
  <!-- Custom js -->
  <script src="{% static 'js/custom.js' %}"></script> 
  
  </body>
</html>